2017-11-29 00:37:07.353 +02:00 [Error] An exception occurred in the database while iterating the results of a query.

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Common.DTO.AnswerDTO.AnswerDTO..ctor(IAnswer answer) в D:\University\3 Курс\QUIZ_TNEU\TNEU\QUIZ\Common\DTO\AnswerDTO\AnswerDTO.cs:строка 19
   в Common.DTO.QuestionDTO.QuestionInfo..ctor(IQuestion question) в D:\University\3 Курс\QUIZ_TNEU\TNEU\QUIZ\Common\DTO\QuestionDTO\QuestionInfo.cs:строка 22
   в lambda_method(Closure , QuestionEntity )
   в Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.<_FirstOrDefault>d__82`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.EntityFrameworkCore.Query.Internal.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
